# AGENTS.md

Instructions for coding agents working in this repository.

## What this project is

A small, reproducible figure pipeline: instrumental and proxy temperature records,
total solar irradiance and CO₂ from 1600 to present, plotted on a common baseline
so that the relative size of the solar and CO₂ signals can be read off directly.

The output is used in public science communication. It will be scrutinised by
people looking for mistakes. A single misplaced shading band or a curve that ends
in the wrong year discredits the whole thing, regardless of whether the underlying
argument is sound.

## The one rule that matters

**Never produce a plotted value that did not come from a data file on disk.**

This project exists because two earlier versions of this figure, generated by LLMs,
contained curves that had been reconstructed from memory rather than loaded. The
symptoms were: CO₂ ending in 1985 at 450 ppm, a satellite record starting 40 years
before the satellite era, missing volcanic cooling signals in a proxy
reconstruction, and shading bands offset by 25 years from their own labels.

Concretely, this means:

- Do not hardcode data points, "representative" values, or smoothed approximations.
- Do not synthesise a series to stand in for one you could not download.
- Do not interpolate across a gap without saying so in the figure.
- If a dataset is unavailable, **stop and report it**. Do not substitute a similar
  dataset while keeping the original label. Using HadCRUT5 and calling it GloSAT is
  a fabrication, not a workaround.
- If you are unsure whether a number is real, it is not. Remove it.

An aborted run is a good outcome. A figure built on data that failed validation is
a bad one.

## Validation is not optional

Every loader must assert expected coverage before the data is used. The `EXPECT`
dict in `climate_figure.py` holds first/last year per series; a violation raises
`DataError` and the process exits non-zero without writing a figure.

Before any figure is written, the QC table must print for each series: first year
and value, last year and value, number of finite points. Do not suppress it, do not
move it after the plot, do not make it conditional on a verbose flag.

When adding a series, add its entry to `EXPECT` and its row to the QC table in the
same commit.

## Data provenance

Raw data lives in `data/` and is **not** committed. See the MANIFEST block at the
top of `climate_figure.py` for sources. Rules:

- Every series in the figure has a matching entry in the MANIFEST with a citation
  and a URL.
- Column names in `CFG` must match the real file headers. Read the header. Do not
  guess and do not assume a file format is stable between releases.
- Do not invent deep links. If you do not know the exact file URL, link the landing
  page and say the path needs checking.
- GloSATref requires a free CEDA account. This is expected; do not route around it.

## Figure conventions

- All temperature series are anomalies relative to **1961–1990**. Series arriving on
  another baseline are re-referenced in code, and the script warns when it does so.
  Never compare anomalies from different baselines.
- Solar minima are drawn at their real extent: Maunder 1645–1715, Dalton 1795–1815.
  After any layout change, verify the bands against the x-axis, not against how they
  look.
- Volcanic markers (1783, 1809, 1815, 1883) are drawn from the x-axis. If a marker
  does not sit over its cooling dip, the axis mapping is broken — do not nudge the
  marker to compensate.
- Radiative forcing comparisons use a **single reference period**, currently
  1750–2019 per IPCC AR6 WG1 Ch.7. A solar term computed from 1600 is a different
  quantity and must be labelled as the deliberately most solar-favourable case, not
  presented alongside a 1750-based CO₂ number as if comparable.
- Splices are marked in the figure: ice core → Mauna Loa, SATIRE-T → SATIRE-S.
  Never join a proxy reconstruction to an instrumental record without an overlap
  region visible to the reader.
- Do not mix lower-troposphere satellite data with surface records in the same
  panel without labelling the difference.

## Analytical honesty

The argument the figure makes is that the early-18th-century warm excursion is
regional, not global. That argument must be supported by *comparable* quantities:
the warming from the Maunder trough (1680–1700 mean) to the peak (1725–1735 mean)
in each series. Differencing absolute anomalies of a regional and a global record
mostly measures the baseline offset between England and the globe, and will be
called out as such.

Any number that appears as text in the figure must be computed from the loaded data
in the same run, not typed into a string literal. If a value cannot be computed,
it does not go in the figure.

## Running

```
python -m venv .venv && . .venv/bin/activate
pip install -r requirements.txt
python climate_figure.py
```

Exit code 0 with `figure_climate_1600_2025.png` written means the run passed
validation. Exit code 1 means a series failed; read stderr, fix the data or the
config, do not weaken the check.

## Style

- Python, stdlib + numpy/pandas/matplotlib. No new dependency without asking.
- Loaders stay dumb: read file, select columns, index by year. Cleverness in a
  loader hides data problems.
- Comments explain why a check exists, not what a line does.

## Before you say you are done

- [ ] Ran the script end to end; QC table pasted into the response.
- [ ] First and last year of every series matches the published record.
- [ ] Shading bands and event markers checked against axis coordinates.
- [ ] Every annotated number traced to a computed value, not a literal.
- [ ] No dataset silently substituted for another.
- [ ] If anything could not be verified, said so plainly instead of omitting it.
